name: githubaction

on:
  push:
    branches:
      - main

jobs:
  testaws:
    name: GithubAction-demo
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::721274598429:role/Githubactionsrole
          aws-region: us-west-1

      - name: Test aws credential
        run: |
          aws s3 ls
